sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t khurramrashid/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true khurramrashid/docker-react2 npm run test
